baseURL: http://www.yunyitang.me/ # ç»‘å®šçš„åŸŸå
languageCode: en
title: Yunyi's Blog
theme: PaperMod 

# change config for posts:
# hugo convert toYAML --config config.yml --unsafe --verbose
# hugo --config config.yml
# before push github: 
# hugo -F --cleanDestinationDir
# local preview: hugo server -D

enableInlineShortcodes: true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage: true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
    en:
        languageName: English
        languageCode: en
        contentDir: content/English
        menu:
          main:
            - identifier: about
              name: About
              url: /en/about/
              weight: 10
            - identifier: project
              name: Project
              url: /en/project/
              weight: 20
            - identifier: resume
              name: Resume
              url: /en/resume.pdf
              weight: 30
            - identifier: tags
              name: ğŸ•¹ï¸
              url: /en/tags/
              weight: 40
            - identifier: search
              name: Search
              url: /en/search/
              weight: 50
        profileMode:
          enabled: true
          title: Yunyi Tang
          subtitle: Little squirrel Hopping around
          imageUrl: "img/Avatar.png"
          imageTitle: 
          imageWidth: 150
          imageHeight: 150
          buttons:
            - name: About
              url: /en/about/
            - name: Project
              url: /en/project/
            - name: Resume
              url: /en/resume.pdf
            - name: Log
              url: /en/blog/tech/log/
    zh:
        languageName: ä¸­æ–‡
        languageCode: zh
        contentDir: content/Chinese
        menu:
          main:
            - identifier: about
              name: å…³äº
              url: /zh/about/
              weight: 10
            - identifier: project
              name: é¡¹ç›®
              url: /zh/project/
              weight: 20
            - identifier: resume
              name: ç®€å†
              url: /zh/resume.pdf
              weight: 30
            - identifier: blog
              name: åšå®¢
              url: /zh/blog/
              weight: 40
            - identifier: links
              name: å‹é“¾
              url: /zh/links/
              weight: 50
            - identifier: tags
              name: ğŸ•¹ï¸
              url: /zh/tags/
              weight: 60
            - identifier: search
              name: æœç´¢
              url: /zh/search/
              weight: 70
        profileMode:
          enabled: true
          title: Yunyi Tang
          subtitle: Little squirrel Hopping around
          imageUrl: "img/Avatar.png"
          imageTitle: 
          imageWidth: 150
          imageHeight: 150
          buttons:
            - name: å…³äº
              url: /zh/about/
            - name: é¡¹ç›®
              url: /zh/project/
            - name: ç®€å†
              url: /zh/resume.pdf
            - name: ğŸ‘©ğŸ»â€ğŸ’»
              url: /zh/blog/tech/

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary for the search function

# è¿™é‡Œçš„å‚æ•°ä¼šè¢«ä»£ç ä»¥ .Site.Params çš„å½¢å¼è¯»å–
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Yunyi's blog, tech, life, data, æŠ€æœ¯åšå®¢"
  author: Yunyi
  defaultTheme: auto  # defaultTheme: light or  dark 
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # éšè—é¡µè„š
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´

  ShowToc: true # æ˜¾ç¤ºç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•

  extendCodeBackground: false # ä»£ç å—æ˜¯å¦è‡ªåŠ¨æ¨ªå‘å±•å¼€

  comments: true 
  twikoo: 
      version: 1.6.27 # è¿™ä¸ªç‰ˆæœ¬å·è¦è‡ªå·±æ‰‹åŠ¨ä¿®æ”¹ï¼Œå’Œtwikooçš„ç‰ˆæœ¬å·è¦å¯¹å¾—ä¸Š
      # tkserver - bdayTtyy!
      # MangoDB yunyit - HsdK3JAKhZbsUnAq Gmail-longin
      # mongodb+srv://yunyit:HsdK3JAKhZbsUnAq@cluster0.p9y20lj.mongodb.net/?retryWrites=true&w=majority
      # https://vercel.com/yunyis-projects/twikoo-api/C5MeWSz2yNXj3RqBa7t23BxjYQDJ 


  socialIcons:
    - name: github
      url: "https://github.com/yunyit"
    - name: linkedin
      url: "https://www.linkedin.com/in/yunyitang820/"
    - name: instagram
      url: "https://www.instagram.com/yunyi_cam/"
    - name: goodreads
      url: "https://www.goodreads.com/user/show/161105203-yunyi-tang"
    - name: email
      url: "mailto:yunyi.tang.820@gmail.com"

  label:
    text: "Home"
    # icon: "img/Icon.png"
    iconHeight: 35
  
  assets:
    # disableHLJS: true 
    favicon: "favicon_io/favicon.ico"
    favicon16x16: "favicon_io/favicon-16x16.png"
    favicon32x32: "favicon_io/favicon-32x32.png"
    apple_touch_icon: "favicon_io/apple-touch-icon.png"
    safari_pinned_tab: "img/Icon.svg"